version: "3"
services:
  dh_auth:
    image: devicehiveci/devicehive-auth:${DH_TAG:-development}

  dh_frontend:
    image: devicehiveci/devicehive-frontend:${DH_TAG:-development}

  hazelcast:
    image: devicehiveci/devicehive-hazelcast:${DH_TAG:-development}

  dh_backend:
    image: devicehiveci/devicehive-backend:${DH_TAG:-development}

  wsproxy:
    image: devicehiveci/devicehive-ws-proxy:${DH_WS_PROXY_TAG:-development}

  dh_proxy:
    image: devicehiveci/devicehive-proxy:${DH_PROXY_TAG:-development}
