version: "3"
services:
  hazelcast:
    links:
      - "hazelcast-mancenter"
    volumes:
      - ./hazelcast.xml:/opt/hazelcast/hazelcast.xml:ro,z

  hazelcast-mancenter:
    image: hazelcast/management-center:3.8.5
    ports:
      - "9980:8080"
    restart: unless-stopped
    volumes:
      - hazelcast-mancenter-data:/data

volumes:
  hazelcast-mancenter-data:
